LDFLAGS += -L/scratch/gnawali/Try/gspc-res/build_dir
LDFLAGS += -L/scratch/gnawali/Try/gspc-res/build_dir/src/util-generic
LDFLAGS += -Wl,-rpath='$$ORIGIN'
LDFLAGS += -Wl,-rpath='/scratch/gnawali/singular-gpispace/spack/opt/spack/linux-debian12-icelake/gcc-12.2.0/gpi-space-24.12-n522f32zjepvd2hhefibm4liumbmbuyu/lib'
LDFLAGS += -Wl,-rpath='/scratch/gnawali/singular-gpispace/spack/opt/spack/linux-debian12-icelake/gcc-12.2.0/gpi-space-24.12-n522f32zjepvd2hhefibm4liumbmbuyu/external/boost/lib'
