CXXFLAGS += -O3
CXXFLAGS += -std=c++17
CXXFLAGS += -I/scratch/gnawali/Try/gspc-res/build_dir
CXXFLAGS += -I/scratch/gnawali/Try/gspc-res/build_dir/template
CXXFLAGS += -I/scratch/gnawali/Try/gspc-res/template
CXXFLAGS += -I/scratch/gnawali/Try/gspc-res/template/src
CXXFLAGS += -I/scratch/gnawali/singular-gpispace/spack/opt/spack/linux-debian12-icelake/gcc-12.2.0/gpi-space-24.12-n522f32zjepvd2hhefibm4liumbmbuyu/include
CXXFLAGS += -I/scratch/gnawali/singular-gpispace/spack/opt/spack/linux-debian12-icelake/gcc-12.2.0/gpi-space-24.12-n522f32zjepvd2hhefibm4liumbmbuyu/external/boost/include
