LDFLAGS += -L/home/santosh/gspc-res/build_dir
LDFLAGS += -L/home/santosh/gspc-res/build_dir/src/util-generic
LDFLAGS += -Wl,-rpath='$$ORIGIN'
LDFLAGS += -Wl,-rpath='/home/santosh/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/gpi-space-24.12-ugaltunbzethad4p3szsepjqdbgthcch/lib'
LDFLAGS += -Wl,-rpath='/home/santosh/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/gpi-space-24.12-ugaltunbzethad4p3szsepjqdbgthcch/external/boost/lib'
