CXXFLAGS += -O3
CXXFLAGS += -std=c++17
CXXFLAGS += -I/home/santosh/gspc-res/build_dir
CXXFLAGS += -I/home/santosh/gspc-res/build_dir/template
CXXFLAGS += -I/home/santosh/gspc-res/template
CXXFLAGS += -I/home/santosh/gspc-res/template/src
CXXFLAGS += -I/home/santosh/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/gpi-space-24.12-ugaltunbzethad4p3szsepjqdbgthcch/include
CXXFLAGS += -I/home/santosh/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/gpi-space-24.12-ugaltunbzethad4p3szsepjqdbgthcch/external/boost/include
